"""P4 finish-time key regression: the content key must reach req.cached_len.

At finish, cached_len = prompt + generated - 1 and the GDN live slot holds the state
after cached_len tokens. If the mm key stops at the prompt end (the old bug), the hybrid
insert truncates the node boundary to the key length: the donated state over-advances the
boundary (a multi-turn continuation would COW-restore a state that already contains the
previous turn's generated tokens) and the generated KV pages are orphaned (leak).

This test drives the REAL CacheManager(hybrid_radix) + REAL LinearStatePool through a
full two-turn lifecycle, mirroring the engine's exact accounting: the forward's
complete_one() sets cached_len = device_len, the scheduler then appends the sampled token
(numel == device_len), and the finishing token is never paged (its KV forward never runs).
GDN state is simulated by a prefix fingerprint on pool.conv_states[0, slot, 0, 0]: the
state "after N tokens" carries sum(ids_all[:N]) (all ids distinct -> prefix sums unique),
which is exactly the invariant the node boundary must honor.

  python -X utf8 verification/p4_finish_key_test.py
"""

import os
import sys

import torch

# SWA decode/extend drivers must fire every step in the SWA legs: set BEFORE the cache
# module is imported (_SWA_EVICTION_INTERVAL is read at import time).
os.environ["FREETOKEN_SWA_EVICTION_INTERVAL"] = "1"

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent.parent / "package"))

from freetoken.core import Req, SamplingParams
from freetoken.kvcache.linear_state_pool import LinearStatePool
from freetoken.models.config import LinearGatedDeltaGroupConfig
from freetoken.scheduler.cache import CacheManager
from freetoken.scheduler.utils import PendingReq
from freetoken.tokenizer import media

FAIL = []
PAD = 151655
N_GEN = 10  # total tokens generated by turn 1 (first sampled in prefill, rest in decode)


def check(name, cond, detail=""):
    print(f"[{'PASS' if cond else 'FAIL'}] {name} {detail}")
    if not cond:
        FAIL.append(name)


def make_group():
    return LinearGatedDeltaGroupConfig(
        name="g", layer_ids=(0,), num_key_heads=1, num_value_heads=1,
        key_head_dim=4, value_head_dim=4, conv_kernel_dim=2, output_gate="silu",
    )


class World:
    """One pool + page table + CacheManager, and the token universe for fingerprints."""

    def __init__(self, ids_all):
        self.ids_all = ids_all  # prompt + generated, all distinct (fingerprint universe)
        self.pool = LinearStatePool(make_group(), num_slots=8, dtype=torch.float32,
                                    device=torch.device("cpu"), tp_size=1)
        self.n_pages = 512
        self.page_table = torch.zeros(32, self.n_pages, dtype=torch.int32)
        self.cm = CacheManager(self.n_pages, 1, self.page_table, "hybrid_radix",
                               linear_state_pool=self.pool)
        self.pc = self.cm.prefix_cache

    def fp(self, slot):
        return float(self.pool.conv_states[0, slot, 0, 0])

    def advance(self, slot, n):
        # state after n tokens = fingerprint of the first n tokens
        self.pool.conv_states[0, slot, 0, 0] = float(sum(self.ids_all[:n]))

    def pages_conserved(self):
        tree_tokens = self.pc.full_evictable + self.pc.full_protected
        return len(self.cm.free_slots) + tree_tokens == self.n_pages, (
            f"free={len(self.cm.free_slots)} tree={tree_tokens} total={self.n_pages}")


# ----------------------------------------------------------------- #
# SWA world: real HybridSWAKVCache (global-paged swa pool) + the     #
# real SWARadixCache via CacheManager("swa_radix") -- the P4 SWA leg.  #
# ----------------------------------------------------------------- #
W_SWA = 4  # small window: the out-of-window free driver engages within N_GEN decode steps


def _ensure_tp() -> None:
    try:
        from freetoken.distributed.info import set_tp_info
        set_tp_info(0, 1)
    except RuntimeError:
        pass  # already set earlier in this process


def _swa_pool(n: int):
    from freetoken.kvcache.hybrid_swa_pool import HybridSWAKVCache
    from freetoken.models.config import KVCacheGroupSpec

    _ensure_tp()
    return HybridSWAKVCache(
        [KVCacheGroupSpec("full", (0,), 1, 4, None),
         KVCacheGroupSpec("swa", (1,), 1, 4, W_SWA)],
        num_layers=2, num_full_pages=n, page_size=1, dtype=torch.float32,
        device=torch.device("cpu"), num_swa_tokens=n)


class WorldSWA:
    """One SWA pool + page table + CacheManager (swa_radix), window W_SWA."""

    def __init__(self, n_pages: int):
        self.n_pages = n_pages
        self.pool = _swa_pool(n_pages)
        self.page_table = torch.zeros(32, n_pages, dtype=torch.int32)
        self.cm = CacheManager(n_pages, 1, self.page_table, "swa_radix",
                               swa_pool=self.pool, sliding_window_size=W_SWA)

    def map_swa(self, full_page) -> int:
        return int(self.pool.full_to_swa_index_mapping[int(full_page)])

    def pc_match(self, ids):
        """match_prefix wrapped in a MatchResult, like CacheManager.match_req for SWA."""
        from freetoken.kvcache import MatchResult
        from freetoken.kvcache.swa_radix_cache import SWACacheHandle

        m = self.cm.prefix_cache.match_prefix(ids)
        return MatchResult(SWACacheHandle(m.cached_len, m.node, m.kv_indices))

    def swa_conserved(self):
        # exact (idle-only) conservation: free swa slots + tree-held live swa == capacity
        tree = self.cm.prefix_cache.swa_evictable + self.cm.prefix_cache.swa_protected
        return (self.pool.swa_available_size() + tree == self.pool.swa_num_tokens - 1,
                f"free={self.pool.swa_available_size()} tree={tree} "
                f"total={self.pool.swa_num_tokens - 1}")

    def pages_conserved(self):
        tree_tokens = self.cm.prefix_cache.full_evictable + self.cm.prefix_cache.full_protected
        return len(self.cm.free_slots) + tree_tokens == self.n_pages, (
            f"free={len(self.cm.free_slots)} tree={tree_tokens} total={self.n_pages}")


def admit_swa(world: WorldSWA, uid, ids, key, mm_embeds=True):
    sp = SamplingParams(max_tokens=N_GEN)
    pr = PendingReq(uid, ids, sp,
                    mm_embeds=torch.zeros(4, 8) if mm_embeds else None,
                    mm_cache_key=key if mm_embeds else None)
    mr = world.cm.match_req(pr)
    req = Req(input_ids=ids, table_idx=0, cached_len=mr.cuda_handle.cached_len,
              output_len=N_GEN, uid=uid, sampling_params=sp,
              cache_handle=mr.cuda_handle,
              mm_embeds=torch.zeros(4, 8) if mm_embeds else None,
              mm_cache_key=key if mm_embeds else None)
    return req, mr


def run_prefill_and_decode_swa(world: WorldSWA, req, plen: int) -> int:
    """Single-chunk prefill + N_GEN generated tokens, engine accounting exactly (SWA legs).
    Mirrors scheduler._prepare_batch: each batch prep runs the swa free driver (decode:
    maybe_free before decode_batch_idx += 1; prefill: free_swa_out_of_window_extend), THEN
    allocate_paged; the forward's complete_one() precedes the scheduler's append_host;
    the chunk commit lands after the first append (scheduler order). The finishing token is
    never paged (its forward never runs). Returns fin = cached_len at finish =
    plen + N_GEN - 1."""
    world.cm.free_swa_out_of_window_extend([req])  # engine: every prefill batch
    world.cm.allocate_paged([req])                 # the prefill chunk: positions 0..plen-1
    req.complete_one()                             # prefill forward tail
    req.append_host(torch.tensor([100], dtype=torch.int32))
    world.cm.cache_req(req, finished=False)        # single-chunk commit (after the append)
    fin = plen + N_GEN - 1
    for j in range(1, N_GEN):
        # decode step j: prep (driver -> idx -> alloc of position plen+j-1), forward, append
        world.cm.maybe_free_swa_out_of_window([req], forward_iter=j)
        req.decode_batch_idx += 1
        world.cm.allocate_paged([req])
        req.complete_one()
        req.append_host(torch.tensor([100 + j], dtype=torch.int32))
    assert req.cached_len == fin, f"cached_len={req.cached_len} want {fin}"
    return fin


def admit(world, uid, ids, key, mm_embeds=True):
    """Fresh admission: match + Req with GDN slots, like PrefillAdder."""
    sp = SamplingParams(max_tokens=N_GEN)
    pr = PendingReq(uid, ids, sp,
                    mm_embeds=torch.zeros(4, 8) if mm_embeds else None,
                    mm_cache_key=key if mm_embeds else None)
    mr = world.cm.match_req(pr)
    live = world.pool.alloc(1)[0]
    pp = tuple(world.pool.alloc(2))
    req = Req(input_ids=ids, table_idx=0, cached_len=mr.cuda_handle.cached_len,
              output_len=N_GEN, uid=uid, sampling_params=sp,
              cache_handle=mr.cuda_handle,
              mm_embeds=torch.zeros(4, 8) if mm_embeds else None,
              mm_cache_key=key if mm_embeds else None,
              linear_slot_idx=live, mamba_ping_pong=pp)
    plen = len(ids)
    world.page_table[0, :plen] = world.cm._allocate(plen)  # like allocate_paged (ps=1)
    return req, mr


def run_prefill_and_decode(world, req, plen):
    """Single-chunk prefill + N_GEN generated tokens, engine accounting exactly.

    Returns fin = cached_len at finish = plen + N_GEN - 1."""
    live = req.linear_slot_idx
    world.advance(live, plen)
    # x64 track during the prefill forward: deepest mid-extend boundary in the ping-pong slot
    track = ((plen - 1) // 64) * 64
    frozen = req.mamba_ping_pong[req.mamba_next_track_idx]
    world.advance(frozen, track)
    req.mamba_last_track_seqlen = track
    req.mamba_next_track_idx = 1 - req.mamba_next_track_idx

    # prefill forward tail: KV valid to plen, first generated token (100) sampled at plen
    req.complete_one()
    world.page_table[0, plen] = world.cm._allocate(1)  # decode page for position plen
    req.append_host(torch.tensor([100], dtype=torch.int32))
    world.cm.cache_req(req, finished=False)  # chunk commit -> donates the track snapshot

    fin = plen + N_GEN - 1
    for j in range(1, N_GEN):
        world.advance(live, plen + j)  # decode forward processes position plen+j-1
        req.append_host(torch.tensor([100 + j], dtype=torch.int32))
        if plen + j < fin:  # the finishing token is never paged (its forward never runs)
            world.page_table[0, plen + j] = world.cm._allocate(1)
        req.complete_one()
    assert req.cached_len == fin, f"cached_len={req.cached_len} want {fin}"
    return fin


def content_key_of(ids, content_id):
    key = ids.clone()
    key[ids == PAD] = content_id
    return key


def main() -> int:
    idA = media._content_id("ft_mm_ababababababababababababababababab.pt")
    idB = media._content_id("ft_mm_cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd.pt")
    assert idA != idB and 1_000_000_000 <= idA < 2_000_000_000

    # fingerprint universe: prompt-shaped (200 distinct ids at the pad span) + generated
    ids_all = [10, 11] + [200 + i for i in range(192)] + [40, 41, 42, 43, 44, 45] \
        + list(range(100, 100 + N_GEN))
    gen_ids = torch.tensor(list(range(100, 100 + N_GEN)), dtype=torch.int32)

    # ---------------- turn 1: image A, 200-token prompt, 10 generated ----------------
    world = World(ids_all)
    P = 200
    idsA = torch.tensor([10, 11] + [PAD] * 192 + [40, 41, 42, 43, 44, 45], dtype=torch.int32)
    keyA = content_key_of(idsA, idA)

    req, mr = admit(world, uid=1, ids=idsA, key=keyA)
    check("admission.cold", mr.cuda_handle.cached_len == 0,
          f"cached_len={mr.cuda_handle.cached_len} (empty tree)")
    fin = run_prefill_and_decode(world, req, P)
    live = req.linear_slot_idx

    world.cm.cache_req(req, finished=True)

    ok, detail = world.pages_conserved()
    check("finish.pages_conserved", ok, detail)
    check("finish.pool_free", world.pool.num_free_slots == 5,
          f"free={world.pool.num_free_slots} (want 5: slots 1-5; 6=snap@track, 7=donated live)")

    # the finish node must sit at cached_len and carry a state matching that boundary
    full_key = torch.cat([keyA, gen_ids])
    m = world.pc.match_prefix(full_key[:fin])
    check("finish.node_at_cached_len", m.cached_len == fin,
          f"boundary={m.cached_len} (want {fin} = prompt+generated-1)")
    want_fp = float(sum(ids_all[:fin]))
    check("finish.state_matches_boundary",
          m.mamba_value == live and abs(world.fp(live) - want_fp) < 1e-3,
          f"slot={m.mamba_value} fp={world.fp(live)} want fp={want_fp} (state after {fin} tokens)")

    # ---- turn 2: same image, turn-1's full response re-included (multi-turn follow-up)
    turn2_ids = torch.cat([idsA, gen_ids, torch.tensor([999, 998, 997], dtype=torch.int32)])
    pr2 = PendingReq(2, turn2_ids, SamplingParams(max_tokens=8),
                     mm_embeds=torch.zeros(4, 8), mm_cache_key=content_key_of(turn2_ids, idA))
    mr2 = world.cm.match_req(pr2)
    check("turn2.full_prefix_reuse", mr2.cuda_handle.cached_len == fin,
          f"cached_len={mr2.cuda_handle.cached_len} (want {fin}: prompt + turn-1 response)")
    check("turn2.state_consistent",
          mr2.mamba_value == live and abs(world.fp(live) - want_fp) < 1e-3,
          f"mamba={mr2.mamba_value} (must restore the state after {fin} tokens, no double-count)")

    # ---- fresh repeat of the same prompt (no response) ----
    # The committed x64 track (192) lands MID-PAD-SPAN (span [2, 194)): matching it would
    # split the pad run across the cache boundary and break the model's splice invariant
    # (the 2026-09-10 production crash: 10 pads in rows vs 1000 soft rows). The fix pulls
    # mid-span matches back to the span start (page-aligned) and drops the snapshot: the
    # whole span re-prefills, all pads in the rows, splice count exact.
    pr3 = PendingReq(3, idsA, SamplingParams(max_tokens=8),
                     mm_embeds=torch.zeros(4, 8), mm_cache_key=keyA)
    mr3 = world.cm.match_req(pr3)
    span_start = 2
    check("repeat.midspan_pulled_back", mr3.cuda_handle.cached_len == span_start,
          f"cached_len={mr3.cuda_handle.cached_len} (want {span_start}: mid-span track 192 "
          "pulled back to the span start; rows carry all 192 pads)")
    check("repeat.mamba_dropped", mr3.mamba_value is None,
          f"mamba={mr3.mamba_value} (snapshot at the uncapped mid-span boundary must not restore)")

    # ---- different image: no false hit ----
    prB = PendingReq(4, idsA, SamplingParams(max_tokens=8),
                     mm_embeds=torch.zeros(4, 8), mm_cache_key=content_key_of(idsA, idB))
    mrB = world.cm.match_req(prB)
    check("diff_image.no_false_hit", mrB.cuda_handle.cached_len == 0,
          f"cached_len={mrB.cuda_handle.cached_len} (content id diverges at first pad)")

    ok, detail = world.pages_conserved()
    check("after_matches.pages_conserved", ok, detail)

    # ---- keyless mm (offline precomputed embeds): no reuse, no insert, no leak ----
    world2 = World(ids_all)
    req2, _ = admit(world2, uid=11, ids=idsA, key=None, mm_embeds=True)
    run_prefill_and_decode(world2, req2, P)
    world2.cm.cache_req(req2, finished=True)
    ok, detail = world2.pages_conserved()
    check("keyless.pages_conserved", ok, detail)
    check("keyless.no_reuse", world2.pc.match_prefix(idsA).cached_len == 0,
          "(keyless mm inserts nothing)")
    check("keyless.pool_free", world2.pool.num_free_slots == 7,
          f"free={world2.pool.num_free_slots} (want 7: nothing donated to the tree)")

    # ---- text regression: same flow, raw ids, boundary must reach cached_len ----
    world3 = World(ids_all[:194] + [600 + i for i in range(1, N_GEN)])
    tids = torch.tensor([10, 11] + [500 + i for i in range(192)], dtype=torch.int32)
    req3, _ = admit(world3, uid=21, ids=tids, key=None, mm_embeds=False)
    fin3 = run_prefill_and_decode(world3, req3, len(tids))
    world3.cm.cache_req(req3, finished=True)
    ok, detail = world3.pages_conserved()
    check("text.pages_conserved", ok, detail)
    m3 = world3.pc.match_prefix(torch.cat([tids, gen_ids])[:fin3])
    check("text.finish_boundary", m3.cached_len == fin3,
          f"boundary={m3.cached_len} (want {fin3}; text key grows with input_ids as before)")
    prT = PendingReq(22, tids, SamplingParams(max_tokens=8))
    mrT = world3.cm.match_req(prT)
    check("text.repeat_track", mrT.cuda_handle.cached_len == 192,
          f"cached_len={mrT.cuda_handle.cached_len}")

    # ================================================================ #
    # SWA legs: real SWARadixCache + real HybridSWAKVCache (window 4).  #
    # The P4 insert keys the commit on the content key; the re-match /  #
    # trim drives (chunk-commit re-point, decode out-of-window free     #
    # floor, finish soft-pin) MUST key on the SAME source, or the floor #
    # under-covers and the drivers free tree-owned swa slots -- the     #
    # exact conservation law below then fires and the follow-up's       #
    # full->swa mapping dangles. Text controls stay bit-identical.      #
    # ================================================================ #
    print()
    print("== SWA legs (real HybridSWAKVCache + SWARadixCache, window=4) ==")

    # ---- turn 1: image A, 200-token prompt (PAD span 2..193), 10 generated ----
    wswa = WorldSWA(512)
    reqS, mrS = admit_swa(wswa, uid=31, ids=idsA, key=keyA)
    check("swa.admission_cold", mrS.cuda_handle.cached_len == 0, "(empty tree)")
    finS = run_prefill_and_decode_swa(wswa, reqS, P)
    # the chunk commit's re-point must cover the WHOLE committed prefix: for a content-keyed
    # mm prompt the raw ids diverge at the first image_pad (pos 2), so a raw re-match would
    # floor at 2 and the decode driver would free the tree-owned [2, 200) swa.
    check("swa.commit_floor", reqS.cache_handle.cached_len == P,
          f"cached_len={reqS.cache_handle.cached_len} (want {P}; the decode floor must cover the commit)")
    # window=4: during decode the driver freed exactly the request's own out-of-window
    # tokens [200, 203) -- nothing tree-owned (the floor protected [0, 200)).
    check("swa.decode_driver_own_slots_only", reqS.swa_evicted_seqlen == 203,
          f"swa_evicted_seqlen={reqS.swa_evicted_seqlen} (want 203 = 3 own tokens out of the window)")

    wswa.cm.cache_req(reqS, finished=True)
    # THE round-2 regression: with the raw-id re-match this assert fired in production's
    # idle poll -- the drivers had freed tree-owned swa slots, breaking the exact law.
    try:
        wswa.cm.check_integrity()
        check("swa.finish_conservation", True, "(check_integrity: free + tree == capacity)")
    except AssertionError as e:
        check("swa.finish_conservation", False, f"({e})")
    ok, detail = wswa.pages_conserved()
    check("swa.finish_pages", ok, detail)
    mS = wswa.pc_match(torch.cat([keyA, gen_ids])[:finS])
    check("swa.finish_node", mS.cuda_handle.cached_len == finS,
          f"boundary={mS.cuda_handle.cached_len} (want {finS})")
    # exact pool accounting: 511 cap - 209 alloc - 3 decode-freed - 180 soft-pin trimmed = 485
    check("swa.pool_exact", wswa.pool.swa_available_size() == 485,
          f"free={wswa.pool.swa_available_size()} (want 485: head [0,180) trimmed, [180,200)+[203,209) retained)")
    pagesS = wswa.page_table[0, :finS]
    # the decode driver freed the request's own [200, 203) (tombstoned at the finish insert);
    # the soft pin kept [180, 200) live and the commit window [203, 209) live.
    liveS = all(wswa.map_swa(p) > 0 for p in pagesS[[*range(180, 200), *range(203, finS)]])
    deadS = all(wswa.map_swa(p) == 0 for p in pagesS[[*range(0, 180), *range(200, 203)]])
    check("swa.retain_window_live", liveS,
          "(soft-pin kept [180, 200) live; commit window [203, 209) live for a next-turn cut)")
    check("swa.head_and_own_freed", deadS, "([0, 180) trimmed + [200, 203) driver-freed -> sentinel)")

    # ---- turn 2: same image, turn-1's full response re-included ----
    t2 = torch.cat([idsA, gen_ids, torch.tensor([999, 998, 997], dtype=torch.int32)])
    pr2s = PendingReq(32, t2, SamplingParams(max_tokens=8),
                      mm_embeds=torch.zeros(4, 8), mm_cache_key=content_key_of(t2, idA))
    mr2s = wswa.cm.match_req(pr2s)
    check("swa.turn2_full_reuse", mr2s.cuda_handle.cached_len == finS,
          f"cached_len={mr2s.cuda_handle.cached_len} (want {finS}: prompt + turn-1 response)")
    # the follow-up's first decode forward reads the window [213-1-4, 213) = [208, 213);
    # its prefix side [208, 209) must be tree pages with LIVE swa mappings (the soft pin
    # kept [P - W - gap, P) = [180, 200) swa-live exactly for this next-turn cut).
    win_lo = t2.numel() - 1 - W_SWA
    reuse_side = mr2s.cuda_handle.kv_indices[win_lo:finS]
    check("swa.turn2_mapping_live", reuse_side.numel() == finS - win_lo
          and all(wswa.map_swa(p) > 0 for p in reuse_side),
          f"(window [{win_lo}, {t2.numel()}) prefix side [{win_lo}, {finS}) -> live swa mappings)")
    ok, detail = wswa.swa_conserved()
    check("swa.turn2_conserved", ok, detail)

    # ---- different image: no false hit ----
    prBs = PendingReq(33, idsA, SamplingParams(max_tokens=8),
                      mm_embeds=torch.zeros(4, 8), mm_cache_key=content_key_of(idsA, idB))
    mrBs = wswa.cm.match_req(prBs)
    check("swa.diff_no_false_hit", mrBs.cuda_handle.cached_len == 0,
          f"cached_len={mrBs.cuda_handle.cached_len} (content id diverges at first pad)")
    ok, detail = wswa.swa_conserved()
    check("swa.after_matches_conserved", ok, detail)

    # ---- keyless mm: no reuse, no insert, no leak ----
    wkl = WorldSWA(512)
    reqK, _ = admit_swa(wkl, uid=41, ids=idsA, key=None)
    run_prefill_and_decode_swa(wkl, reqK, P)
    wkl.cm.cache_req(reqK, finished=True)
    ok, detail = wkl.pages_conserved()
    check("swa.keyless_pages", ok, detail)
    check("swa.keyless_no_reuse", wkl.pc_match(idsA).cuda_handle.cached_len == 0,
          "(keyless mm inserts nothing)")
    ok, detail = wkl.swa_conserved()
    check("swa.keyless_conserved", ok, f"(all 209 slots returned: {detail})")

    # ---- text control: same flow on raw ids, exactly conserved ----
    wtx = WorldSWA(512)
    tids = torch.tensor([10, 11] + [500 + i for i in range(192)], dtype=torch.int32)
    reqX, mrX = admit_swa(wtx, uid=51, ids=tids, key=None, mm_embeds=False)
    finX = run_prefill_and_decode_swa(wtx, reqX, len(tids))
    check("swa.text_commit_floor", reqX.cache_handle.cached_len == len(tids),
          f"cached_len={reqX.cache_handle.cached_len} (want {len(tids)})")
    wtx.cm.cache_req(reqX, finished=True)
    ok, detail = wtx.pages_conserved()
    check("swa.text_pages", ok, detail)
    mX = wtx.pc_match(torch.cat([tids, gen_ids])[:finX])
    check("swa.text_finish_node", mX.cuda_handle.cached_len == finX,
          f"boundary={mX.cuda_handle.cached_len} (want {finX})")
    # 511 - 203 alloc + 3 decode-freed + 174 soft-pin trimmed = 485; tree retains 20 + 6
    check("swa.text_pool_exact", wtx.pool.swa_available_size() == 485,
          f"free={wtx.pool.swa_available_size()} (want 485)")
    prX = PendingReq(52, tids, SamplingParams(max_tokens=8))
    mrX2 = wtx.cm.match_req(prX)
    # a prompt-only repeat matches on input_ids[:input_len-1] = 193 tokens; the soft pin kept
    # [174, 194) live, so the live run [174, 193) covers the window and the WHOLE key reuses.
    check("swa.text_repeat", mrX2.cuda_handle.cached_len == len(tids) - 1,
          f"cached_len={mrX2.cuda_handle.cached_len} (want {len(tids) - 1}: full key, window-covered)")
    ok, detail = wtx.swa_conserved()
    check("swa.text_conserved", ok, detail)

    print()
    if FAIL:
        print(f"RESULT: {len(FAIL)} FAILURE(S): {FAIL}")
        return 1
    print("RESULT: ALL PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
